(materia (codigo 1) (nombre "ADMINISTRACION DE LA PRODUCCION") (tutoria 0) )
(materia (codigo 2) (nombre "ADMINISTRACION DE PROYECTOS") (tutoria 0) )
(materia (codigo 3) (nombre "BIOETICA") (tutoria 0) )
(materia (codigo 4) (nombre "BIOGEOGRAFIA ECOLOGICA") (tutoria 1) )
(materia (codigo 5) (nombre "BIOINFORMATICA") (tutoria 0) )
(materia (codigo 6) (nombre "CALCULO DE VARIAS VARIABLES") (tutoria 1) )
(materia (codigo 7) (nombre "CALCULO DIFERENCIAL") (tutoria 1) )
(materia (codigo 8) (nombre "CALCULO ESTRUCTURAL ESTATICO") (tutoria 1) )
(materia (codigo 9) (nombre "CALCULO INTEGRAL") (tutoria 1) )
(materia (codigo 10) (nombre "DINAMICA") (tutoria 0) )